#!/bin/bash
set -eo pipefail

apt-get update
apt-get install -y build-essential python2-dev virtualenv

venv_path=/home/vagrant/virtualenv

virtualenv --python 2 "$venv_path"
source "${venv_path}/bin/activate"
pip install autobahntestsuite

bash_profile=/home/vagrant/.bash_aliases
touch "$bash_profile"

if ! grep -q virtualenv "$bash_profile" ; then
  echo 'source ~/virtualenv/bin/activate' >> "$bash_profile"
fi
