#!/bin/bash

# This install script has been tested on Ubuntu 20.04. More recent releases
# have openssl versions that Python's cryptography package do not build
# against, when using a version that will install on Python 2.7.

VENV_PATH="$HOME/venv"
BASHRC="$HOME/.bash_aliases"

sudo apt-get update
sudo apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    python2-dev \
    virtualenv

if [[ ! -d "$VENV_PATH" ]] ; then
  virtualenv --python 2 "$VENV_PATH"
  source "${VENV_PATH}/bin/activate"
  pip install typing
  pip install --no-use-pep517 -r requirements.txt
fi

touch "$BASHRC"

if ! grep -q venv "$BASHRC" ; then
  echo 'source ~/venv/bin/activate' >> "$BASHRC"
fi
