#!/bin/bash
set -eo pipefail

install-nvm() {
  local version="$1"

  cd /usr/local/src
  [[ -d nvm ]] || git clone git://github.com/nvm-sh/nvm.git
  cd nvm
  git fetch
  git checkout "v${version}"

  local bash_profile=/home/vagrant/.bash_aliases
  touch "$bash_profile"

  if ! grep -q nvmrc "$bash_profile" ; then
    cat > /home/vagrant/.nvmrc <<-EOF
      export NVM_DIR=/opt/node
      source /usr/local/src/nvm/nvm.sh
EOF
    echo 'source ~/.nvmrc' >> "$bash_profile"
  fi

  mkdir -p /opt/node
}

apt-get update
apt-get install -y build-essential
mkdir -p /usr/local/src

install-nvm 0.37.2
source /home/vagrant/.nvmrc
nvm alias default stable

for version in 0.{8,10,12} {4..16} ; do
  nvm install "$version"
done
