#!/usr/bin/env bash

NVM_VERSION='v0.39.5'
NODE_VERSIONS=(0.{8,10,12} $(seq 4 2 24))

NVM_DIR=~/opt/node
RCFILE=~/opt/.nvmrc
BASHRC=~/.bash_aliases
ORIG_PWD="$PWD"

if [[ $# -gt 0 ]] ; then
  source "$RCFILE"
  nvm install "$1"
  exit
fi

sudo apt-get update
sudo apt-get install -y build-essential

mkdir -p "$NVM_DIR"
cd ~/opt
if [[ ! -d nvm ]] ; then
  git clone https://github.com/nvm-sh/nvm.git
fi
cd nvm
git fetch
git checkout "$NVM_VERSION"

touch "$BASHRC"

if [[ ! -f "$RCFILE" ]] ; then
  cat > "$RCFILE" <<-EOF
    export NVM_DIR=$NVM_DIR
    source ~/opt/nvm/nvm.sh
EOF
  echo "source $RCFILE" >> "$BASHRC"
fi

source "$RCFILE"
nvm alias default 'lts/*'

cd "$ORIG_PWD"

for version in "${NODE_VERSIONS[@]}" ; do
  ./install/node "$version"
done
