#!/bin/bash

NVM_VERSION='v0.39.5'
NODE_VERSIONS=(0.{8,10,12} $(seq 4 2 24))
NVM_DIR=~/src/node

BASHRC=~/.bash_aliases

sudo apt-get update
sudo apt-get install -y build-essential

mkdir -p "$NVM_DIR"
cd ~/src
if [[ ! -d nvm ]] ; then
  git clone https://github.com/nvm-sh/nvm.git
fi
cd nvm
git fetch
git checkout "$NVM_VERSION"

touch "$BASHRC"

if [[ ! -f ~/src/.nvmrc ]] ; then
  cat > ~/src/.nvmrc <<-EOF
    export NVM_DIR=$NVM_DIR
    source ~/src/nvm/nvm.sh
EOF
  echo 'source ~/src/.nvmrc' >> "$BASHRC"
fi

source ~/src/.nvmrc
nvm alias default 'lts/*'

for version in "${NODE_VERSIONS[@]}" ; do
  nvm install "$version"
done
