#!/bin/bash
set -eo pipefail
source ~/.nvmrc
source ~/.rubyrc


node-client() {
  local version="$1"

  cd ~/src/node/websocket
  nvm use "$version"
  node examples/autobahn_client.js
}

for version in 0.{8,10,12} {4..15} ; do
  node-client "$version"
done


ruby-client() {
  local version="$1"

  cd ~/src/ruby/$version/websocket
  chruby "$version"
  compile-driver
  ruby examples/autobahn_client.rb
}

compile-driver() {
  cd ../driver
  ruby -S bundle exec rake compile
  cd -
}

for version in 1.9 2.{0..7} 3.0 ; do
  ruby-client "ruby-$version"
done

cd ~/src/ruby/jruby-1.7/websocket
chruby jruby-1.7
compile-driver
ruby -J-Xmx2048m --1.9 examples/autobahn_client.rb
ruby -J-Xmx2048m --2.0 examples/autobahn_client.rb

ruby-client jruby-9.1
ruby-client jruby-9.2
