#!/bin/bash
set -eo pipefail
source ~/.nvmrc


websocket-driver-node-server () {
  local version="$1"
  local port="$2"

  cd ~/repo/node/driver
  nvm use "$version"
  node examples/net_server.js "$port" &
}

websocket-driver-node-server  4     4001
websocket-driver-node-server  6     4002
websocket-driver-node-server  8     4003
websocket-driver-node-server  10    4004
websocket-driver-node-server  12    4005
websocket-driver-node-server  14    4006
websocket-driver-node-server  16    4007
websocket-driver-node-server  18    4008
websocket-driver-node-server  20    4009


faye-websocket-node-server () {
  local version="$1"
  local port="$2"

  cd ~/repo/node/websocket
  nvm use "$version"
  node examples/server.js "$port" &
}

faye-websocket-node-server  4     5001
faye-websocket-node-server  6     5002
faye-websocket-node-server  8     5003
faye-websocket-node-server  10    5004
faye-websocket-node-server  12    5005
faye-websocket-node-server  14    5006
faye-websocket-node-server  16    5007
faye-websocket-node-server  18    5008
faye-websocket-node-server  20    5009
