#!/bin/bash
set -eo pipefail
source ~/.rubyrc


compile-driver () {
  cd ../driver
  ruby -S bundle exec rake compile
  cd -
}


websocket-driver-ruby-server () {
  local version="$1"
  local port="$2"

  cd ~/repo/ruby/$version/driver
  chruby "$version"
  compile-driver
  ruby examples/em_server.rb "$port" &
}

websocket-driver-ruby-server  ruby-2.1  6101
websocket-driver-ruby-server  ruby-2.2  6102
websocket-driver-ruby-server  ruby-2.3  6103
websocket-driver-ruby-server  ruby-2.4  6104
websocket-driver-ruby-server  ruby-2.5  6105
websocket-driver-ruby-server  ruby-2.6  6106
websocket-driver-ruby-server  ruby-2.7  6107
websocket-driver-ruby-server  ruby-3.0  6108
websocket-driver-ruby-server  ruby-3.1  6109
websocket-driver-ruby-server  ruby-3.2  6110
websocket-driver-ruby-server  ruby-3.3  6111
websocket-driver-ruby-server  ruby-3.4  6112

# cd ~/repo/ruby/jruby-1.7/driver
# chruby jruby-1.7
# ruby -S bundle exec rake compile
# ruby -J-Xmx2048m --1.9 examples/em_server.rb 6201 &
# ruby -J-Xmx2048m --2.0 examples/em_server.rb 6202 &

websocket-driver-ruby-server jruby-9.1 6203
websocket-driver-ruby-server jruby-9.2 6204
websocket-driver-ruby-server jruby-9.3 6205
websocket-driver-ruby-server jruby-9.4 6206


faye-websocket-ruby-server () {
  local version="$1"
  local server="$2"
  local port="$3"

  cd ~/repo/ruby/$version/websocket
  chruby "$version"
  compile-driver
  ruby examples/server.rb "$port" '' "$server" &
}

faye-websocket-ruby-server  ruby-2.1  thin  7101
faye-websocket-ruby-server  ruby-2.2  thin  7102
faye-websocket-ruby-server  ruby-2.3  thin  7103
faye-websocket-ruby-server  ruby-2.4  thin  7104
faye-websocket-ruby-server  ruby-2.5  thin  7105
faye-websocket-ruby-server  ruby-2.6  thin  7106
faye-websocket-ruby-server  ruby-2.7  thin  7107
faye-websocket-ruby-server  ruby-3.0  thin  7108
faye-websocket-ruby-server  ruby-3.1  thin  7109
faye-websocket-ruby-server  ruby-3.2  thin  7110
faye-websocket-ruby-server  ruby-3.3  thin  7111
faye-websocket-ruby-server  ruby-3.4  thin  7112

cd ~/repo/ruby/ruby-3.1/websocket
chruby ruby-3.1
ruby examples/server.rb 7201 '' goliath -svp 7201 &
cd examples
ruby -S bundle exec passenger start -p 7202 &

faye-websocket-ruby-server  ruby-3.2  puma      7203
faye-websocket-ruby-server  ruby-3.2  rainbows  7204

# cd ~/repo/ruby/jruby-1.7/websocket
# chruby jruby-1.7
# ruby -J-Xmx2048m --1.9 examples/server.rb 7301 '' puma &
# ruby -J-Xmx2048m --2.0 examples/server.rb 7302 '' puma &

faye-websocket-ruby-server jruby-9.1 puma 7303
# faye-websocket-ruby-server jruby-9.2 puma 7304
# faye-websocket-ruby-server jruby-9.3 puma 7305
# faye-websocket-ruby-server jruby-9.4 puma 7306
