#!/bin/bash

set -e
. /usr/local/opt/nvm/nvm.sh
. /usr/local/share/chruby/chruby.sh


function run-node-client() {
  nvm use $1
  node examples/autobahn_client.js
}

cd .code/node/websocket
run-node-client 0.8
run-node-client 0.10
run-node-client 0.12
run-node-client 4
run-node-client 5
run-node-client 6
run-node-client 7
cd -


function run-ruby-client() {
  chruby $1
  compile-driver
  ruby examples/autobahn_client.rb
}

function compile-driver() {
  cd ../driver
  ruby -S bundle exec rake compile
  cd -
}

cd .code/ruby/websocket
run-ruby-client 1.9.3
run-ruby-client 2.0.0
run-ruby-client 2.1.10
run-ruby-client 2.2.6
run-ruby-client 2.3.3
run-ruby-client 2.4.0

chruby jruby-1.7
compile-driver
ruby -J-Xmx2048m --1.9 examples/autobahn_client.rb
ruby -J-Xmx2048m --2.0 examples/autobahn_client.rb
