#!/bin/bash

set -e
. /usr/local/opt/nvm/nvm.sh
. /usr/local/share/chruby/chruby.sh


function run-node-client() {
  cd .code/node/websocket
  nvm use "$1"
  node examples/autobahn_client.js
  cd -
}

run-node-client 0.8
run-node-client 0.10
run-node-client 0.12
run-node-client 4
run-node-client 5
run-node-client 6
run-node-client 7
run-node-client 8


function run-ruby-client() {
  cd ".code/ruby/$1/websocket"
  chruby "$1"
  compile-driver
  ruby examples/autobahn_client.rb
  cd ../../../..
}

function compile-driver() {
  cd ../driver
  ruby -S bundle exec rake compile
  cd -
}

run-ruby-client 1.9.3
run-ruby-client 2.0.0
run-ruby-client 2.1.10
run-ruby-client 2.2.7
run-ruby-client 2.3.4
run-ruby-client 2.4.1

cd .code/ruby/jruby-1.7/websocket
chruby jruby-1.7
compile-driver
ruby -J-Xmx2048m --1.9 examples/autobahn_client.rb
ruby -J-Xmx2048m --2.0 examples/autobahn_client.rb
cd ../../../..

cd .code/ruby/jruby-9/websocket
chruby jruby-9
compile-driver
ruby -J-Xmx2048m examples/autobahn_client.rb
